# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-03-16T18:54:22Z"
  generation: 2
  labels:
    app: demo-smartsearch
  name: demo-smartsearch
  namespace: default
  resourceVersion: "455635"
  uid: d5437657-6c65-4196-be28-cf6f5fef71b3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-smartsearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-smartsearch
    spec:
      containers:
      - env:
        - name: LEMMATIZER_IP
          value: 10.97.39.234
        image: tilluteenused/demo_smartsearch_webpage:2023.03.14
        imagePullPolicy: IfNotPresent
        name: demo-smartsearch-webpage-qsxm7
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-16T18:54:23Z"
    lastUpdateTime: "2023-03-16T18:54:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-16T18:54:22Z"
    lastUpdateTime: "2023-03-16T19:01:24Z"
    message: ReplicaSet "demo-smartsearch-6c5688d6b4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

