# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-03-15T20:22:27Z"
  generation: 1
  labels:
    app: lemmatiseerija
  name: lemmatiseerija
  namespace: default
  resourceVersion: "390031"
  uid: 9ac35881-75b2-4306-a665-9cda43b033f8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lemmatiseerija
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lemmatiseerija
    spec:
      containers:
      - image: tilluteenused/lemmatiseerija:2023.03.14
        imagePullPolicy: IfNotPresent
        name: lemmatiseerija
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-15T20:22:28Z"
    lastUpdateTime: "2023-03-15T20:22:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-15T20:22:27Z"
    lastUpdateTime: "2023-03-15T20:22:28Z"
    message: ReplicaSet "lemmatiseerija-55bc5f94cb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
